---
# Copyright (c) IBM Corporation 2021

galaxy_info:
  role_name: powervc_create_network_ports
  author: Osman Omer
  description: Ansible role for creating new network ports to specify the IP addresses to be used on the nodes
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions: 
    - 7.2
    - 7.3

  galaxy_tags: [aix]
  dependencies: []
